services:
  waf2py:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: waf2py
    ports:
      - "62443:62443"
    restart: unless-stopped
    entrypoint: /usr/local/bin/entrypoint.sh
    networks:
      - sec-tools

networks:
  sec-tools:
    name: sec-tools
    driver: bridge
